version: '3'
services:
  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - 3306
    environment:
      - MYSQL_DATABASE=judgedb
      - MYSQL_ROOT_PASSWORD=mitra1341

  web:
    build: .
    command: python manage.py runserver host.docker.internal:8000
    ports:
      - "8000:8000"
    depends_on:
      - db

