# Generated by Django 2.1.7 on 2019-04-04 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0002_auto_20190404_2202'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='score',
            field=models.PositiveIntegerField(blank=True, default=100, null=True),
        ),
    ]
