# Generated by Django 3.1.6 on 2021-02-11 20:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('problems', '0003_problem_score'),
        ('submissions', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mainsubmission',
            name='sidno',
        ),
        migrations.AddField(
            model_name='submissioncache',
            name='judged',
            field=models.CharField(blank=True, default='no', max_length=5),
        ),
        migrations.AlterField(
            model_name='mainsubmission',
            name='execution_time',
            field=models.DecimalField(blank=True, decimal_places=3, default=0, max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='mainsubmission',
            name='language',
            field=models.CharField(blank=True, choices=[('c_cpp', 'C++')], default='c_cpp', max_length=100),
        ),
        migrations.AlterField(
            model_name='mainsubmission',
            name='problem_submitted',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='problem_m_submission', to='problems.problem'),
        ),
        migrations.AlterField(
            model_name='mainsubmission',
            name='user_handle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_m_submission', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='mainsubmission',
            name='verdict',
            field=models.CharField(blank=True, default='...', max_length=500),
        ),
        migrations.AlterField(
            model_name='submissioncache',
            name='language',
            field=models.CharField(blank=True, choices=[('c_cpp', 'C++')], default='c_cpp', max_length=100),
        ),
        migrations.AlterField(
            model_name='submissioncache',
            name='problem_submitted',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='problem_c_submission', to='problems.problem'),
        ),
        migrations.AlterField(
            model_name='submissioncache',
            name='user_handle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_c_submission', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Leaderboard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank', models.PositiveIntegerField(blank=True, null=True)),
                ('user_handle', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_leaderboard', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
