# Generated by Django 3.1.6 on 2021-02-15 13:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('submissions', '0002_auto_20210212_0021'),
    ]

    operations = [
        # migrations.CreateModel(
        #     name='Leaderboard',
        #     fields=[
        #         ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
        #         ('rank', models.PositiveIntegerField(blank=True, null=True)),
        #         ('user_handle', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_leaderboard', to=settings.AUTH_USER_MODEL)),
        #     ],
        # ),
    ]
