# Generated by Django 2.1.7 on 2019-03-24 14:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coders', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userprofile',
            options={'permissions': (('can_go_in_non_ac_bus', 'To provide non-AC Bus facility'), ('can_go_rishikesh', 'Trip to Rishikesh'))},
        ),
    ]
