# Generated by Django 3.1.6 on 2021-02-09 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coders', '0006_faqs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='first_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='first name'),
        ),
    ]
